name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"
    - cron: "30 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secret_file: [CONFIG_JSON_1, CONFIG_JSON_2] # 替换为您的 Secrets 名称

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      # 安装依赖
      - name: 安装依赖
        run: pip install -r requirements.txt

      # 调试 matrix.secret_file
      - name: 调试 matrix.secret_file
        run: |
          echo "当前处理的 Secret 名称为：${{ matrix.secret_file }}"

      # 写入 Secrets 到多个 JSON 文件
      - name: 写入 Secrets 到 JSON 文件
        run: |
          mkdir -p user
          SECRET="${{ secrets[matrix.secret_file] }}"
          if [ -z "$SECRET" ]; then
            echo "Secret for ${{ matrix.secret_file }} 未定义或为空，跳过。"
            exit 1
          fi
          echo "$SECRET" | jq . > "user/config_${{ matrix.secret_file }}.json"
          echo "写入完成：user/config_${{ matrix.secret_file }}.json"

      # 验证文件是否正确写入
      - name: 验证 JSON 文件
        run: |
          if [ -s "user/config_${{ matrix.secret_file }}.json" ]; then
            echo "文件 user/config_${{ matrix.secret_file }}.json 写入成功。"
            cat "user/config_${{ matrix.secret_file }}.json"
          else
            echo "文件 user/config_${{ matrix.secret_file }}.json 写入失败！"
            exit 1
          fi

      # 执行签到脚本
      - name: 执行签到脚本
        run: python main.py
