name: test

on:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:  # 手动触发支持

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Save JSON Secret to file
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          mkdir -p user
          echo "$CONFIG_JSON" > user/config.json

      - name: Check if config.json exists and show contents
        run: |
          if [ -f user/config.json ]; then
            echo "config.json 文件存在，内容如下:"
            cat user/config.json
          else
            echo "config.json 文件不存在"
          fi

      - name: Debug CONFIG_JSON secret (Optional, remove in production)
        run: |
          echo "Debugging CONFIG_JSON secret: $CONFIG_JSON"
        
      - name: Run Auto Check-In
        env:
          USERNAME: ${{ secrets.MOGUDING_USERNAME }}
          PASSWORD: ${{ secrets.MOGUDING_PASSWORD }}
        run: python main.py
