name: 测试写入 Secrets 到文件并验证 JSON 格式

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      # 安装依赖
      - name: 安装依赖
        run: pip install -r requirements.txt

      # 输出 Secrets 内容进行调试
      - name: 输出 Secrets 内容进行调试
        run: |
          echo "Secrets 内容如下："
          echo "$TEST_SECRET" 

      # 写入 Secrets 到 config.json
      - name: 写入 Secrets 到 config.json
        env:
          TEST_SECRET: ${{ secrets.CONFIG_JSON }}
        run: |
          mkdir -p user
          echo "$TEST_SECRET" > user/config.json
          echo "写入完成。"

      # 验证文件是否正确写入
      - name: 验证文件是否正确写入
        run: |
          if [ -s user/config.json ]; then
            echo "Secrets 文件已成功写入，大小为：$(stat -c%s user/config.json) 字节"
          else
            echo "Secrets 文件为空或写入失败！"
            exit 1
          fi

      # 验证 config.json 内容
      - name: 验证 config.json 内容
        run: |
          echo "字符总数为：$(wc -c < user/config.json)"

      # 执行签到脚本
      - name: 执行签到脚本
        run: python main.py
