name: test

on:
  schedule:
    # 北京时间 8:00（对应 UTC 时间 0:00）
    - cron: "0 0 * * *"
    # 北京时间 18:00（对应 UTC 时间 10:00）
    - cron: "0 10 * * *"
    # 当前时间下一分钟（以北京时间 14:28 为例，转换为 UTC 6:29）
    - cron: "51 4 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Auto Check-In
        env:
          USERNAME: ${{ secrets.MOGUDING_USERNAME }}
          PASSWORD: ${{ secrets.MOGUDING_PASSWORD }}
        run: python main.py
