name: 测试写入 Secrets 到文件并验证 JSON 格式

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 创建 user 目录并写入 Secrets 测试
        env:
          TEST_SECRET: ${{ secrets.CONFIG_JSON }}
        run: |
          mkdir -p user
          echo "正在写入 Secrets 到 user/test_secrets.txt..."
          echo "$TEST_SECRET" > user/test_secrets.txt
          echo "写入完成。"

      - name: 安装 jq 工具
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: 验证 JSON 格式
        run: |
          if jq empty user/test_secrets.txt; then
            echo "Secrets 文件包含有效的 JSON 内容！"
          else
            echo "Secrets 文件的 JSON 格式无效！"
          fi

      - name: 验证文件大小
        run: |
          if [ -s user/test_secrets.txt ]; then
            echo "Secrets 文件已写入，大小为：$(stat -c%s user/test_secrets.txt) 字节"
          else
            echo "Secrets 文件为空或未正确写入！"
          fi
