name: 测试写入功能

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 创建 user 目录并写入 test.txt
        run: |
          mkdir -p user
          echo "这是一个测试文件。" > user/test.txt
          echo "test.txt 写入完成，内容如下："
          cat user/test.txt || echo "test.txt 写入失败"

      - name: 检查 test.txt 文件是否存在
        run: |
          if [ -f user/test.txt ]; then
            echo "test.txt 文件存在，内容如下："
            cat user/test.txt
          else
            echo "test.txt 文件不存在！"
          fi
