name: 自动签到任务

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 保存 CONFIG_JSON 到文件
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          mkdir -p user
          echo "${CONFIG_JSON}" | jq '.' > user/config.json
          echo "config.json 写入完成，内容如下："
          cat user/config.json

      - name: 检查并显示 config.json 内容
        run: |
          if [ -f user/config.json ]; then
            echo "config.json 文件存在，内容如下："
            cat user/config.json
          else
            echo "config.json 文件不存在！"
          fi

      - name: 运行自动签到
        env:
          USERNAME: ${{ secrets.MOGUDING_USERNAME }}
          PASSWORD: ${{ secrets.MOGUDING_PASSWORD }}
        run: python main.py
